# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0efb4344a9699d209defb802e3e80d581cbd8c8ae567bdf5abb8c48f3977cc528ff0697d9dfc32e24611c1403157487a705736e9ae5fde7d22c38fb0941af4d2

test:
  secret_key_base: acad4d601d7c43711c89dc0d274e9915c42838c840f7a2b4d5e286a6ff83d3c0bbf92daa3e6f54ca865290d4a9107c124f3b9983720e5d8128c904bdd226d88b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
